### ISSUE TITLE
Bug with musicxml Import

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#161]
Load `.musicxml` fails with Error:
```shell
Traceback (most recent call last):
    score = pt.load_musicxml(score)
  File "/partitura/partitura/utils/misc.py", line 49, in wrapper
    return f(*args, **kwargs)
  File "partitura/partitura/utils/misc.py", line 71, in wrapper
    return f(*args, **kwargs)
  File "partitura/partitura/io/importmusicxml.py", line 231, in load_musicxml
    _parse_parts(document, part_dict)
  File "partitura/partitura/io/importmusicxml.py", line 362, in _parse_parts
    start_times = [0] + [r.end.t for r in part.iter_all(score.Repeat)]
  File "partitura/partitura/io/importmusicxml.py", line 362, in <listcomp>
    start_times = [0] + [r.end.t for r in part.iter_all(score.Repeat)]
AttributeError: 'NoneType' object has no attribute 't'
```

[AlbinoniT-O6N10-4.zip](https://github.com/CPJKU/partitura/files/9747933/AlbinoniT-O6N10-4.zip)

**Comment by sildater** [comment]
Can you send me the file that produces the error?

**Comment by manoskary** [comment]
> Can you send me the file that produces the error?

It's already attached.
