### ISSUE TITLE
documentation updates don't show up on readthedocs

### ISSUE THREAD

**Issue by sildater** [CPJKU/partitura#289]
documentation changes seem to be missing on readthedocs. compare the new (v1.3.0) `Additional Resources` content in the intro `partitura\docs\source\introduction.rst` to the [read the docs intro](https://partitura.readthedocs.io/en/latest/introduction.html)

**Comment by manoskary** [comment]
I found the issue. Error log:
```shell
/home/docs/checkouts/readthedocs.org/user_builds/partitura/checkouts/v1.2.2/docs/source/Tutorial/notebook.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/partitura/envs/v1.2.2/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 1093, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/partitura/envs/v1.2.2/lib/python3.8/site-packages/readthedocs_ext/readthedocs.py", line 185, in rtd_render
    content = old_render(template, render_context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/partitura/envs/v1.2.2/lib/python3.8/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
  File "/home/docs/checkouts/readthedocs.org/user_builds/partitura/envs/v1.2.2/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/docs/checkouts/readthedocs.org/user_builds/partitura/envs/v1.2.2/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/docs/checkouts/readthedocs.org/user_builds/partitura/envs/v1.2.2/lib/python3.8/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/home/docs/checkouts/readthedocs.org/user_builds/partitura/envs/v1.2.2/lib/python3.8/site-packages/sphinx_rtd_theme/layout.html", line 67, in top-level template code
    <link rel="stylesheet" href="{{ pathto('_static/' + style, 1) }}" type="text/css" />
jinja2.exceptions.UndefinedError: 'style' is undefined
```

Probably the compilation of the docs compatible with the newest nbsphinx version. I will try to fix it by setting it to a previous one.

**Comment by sildater** [comment]
I think the documentation is still on version 1.1.1

**Comment by manoskary** [comment]
No, I can see that it is showing 1.3.1 compiled.

**Comment by sildater** [comment]
here: https://partitura.readthedocs.io/en/latest/ ?
