### ISSUE TITLE
Tuplet errors when parsing some scores

### ISSUE THREAD

**Issue by leleogere** [CPJKU/partitura#386]
Hello,

I'm currently bulk processing scores from the (n)-ASAP dataset, and I'm facing tuplet errors when loading some scores. They might be due to a bad MusicXML encoding, but I thought that it might be interesting to report them here in case the issue comes from Partitura.

The reported error is the following:
```py
Traceback (most recent call last):
  File "/home/user/test.py", line 236, in <module>
    score = pt.load_musicxml(path)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/env/lib/python3.12/site-packages/partitura/utils/misc.py", line 68, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/env/lib/python3.12/site-packages/partitura/utils/misc.py", line 90, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/env/lib/python3.12/site-packages/partitura/io/importmusicxml.py", line 255, in load_musicxml
    _parse_parts(document, part_dict)
  File "/home/user/miniconda3/envs/env/lib/python3.12/site-packages/partitura/io/importmusicxml.py", line 370, in _parse_parts
    position, doc_order = _handle_measure(
                          ^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/env/lib/python3.12/site-packages/partitura/io/importmusicxml.py", line 588, in _handle_measure
    (position, prev_note, prev_beam) = _handle_note(
                                       ^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/env/lib/python3.12/site-packages/partitura/io/importmusicxml.py", line 1391, in _handle_note
    starting_tups, stopping_tups = handle_tuplets(notations, ongoing, note)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/env/lib/python3.12/site-packages/partitura/io/importmusicxml.py", line 1456, in handle_tuplets
    start_tuplet.start_note.start.t < stop_tuplet.end_note.start.t
AssertionError: Tuplet start time is after tuplet stop time
```

Here is a list of a few affected files. There might be more, but I haven't tested the whole dataset yet, I can update this list later if needed.
[Bach/Prelude/bwv_874](https://github.com/CPJKU/asap-dataset/blob/main/Bach/Prelude/bwv_874/xml_score.musicxml)
[Balakirev/Islamey](https://github.com/CPJKU/asap-dataset/blob/main/Balakirev/Islamey/xml_score.musicxml)
[Beethoven/Piano_Sonatas/13-4](https://github.com/CPJKU/asap-dataset/blob/main/Beethoven/Piano_Sonatas/13-4/xml_score.musicxml)
[Beethoven/Piano_Sonatas/16-2](https://github.com/CPJKU/asap-dataset/blob/main/Beethoven/Piano_Sonatas/16-2/xml_score.musicxml)
[Beethoven/Piano_Sonatas/17-3](https://github.com/CPJKU/asap-dataset/blob/main/Beethoven/Piano_Sonatas/17-3/xml_score.musicxml)
[Beethoven/Piano_Sonatas/18-3](https://github.com/CPJKU/asap-dataset/blob/main/Beethoven/Piano_Sonatas/18-3/xml_score.musicxml)
[Beethoven/Piano_Sonatas/22-1](https://github.com/CPJKU/asap-dataset/blob/main/Beethoven/Piano_Sonatas/22-1/xml_score.musicxml)

**Comment by manoskary** [comment]
Hello Leo and thanks for your issue, it is indeed slight issues with the scores, I propose to relax the condition to `start_tuplet.start_note.start.t <= stop_tuplet.end_note.start.t`
