### ISSUE TITLE
Attribute Error in Match 3.1 when reading Time Signature

### ISSUE THREAD

**Issue by manoskary** [CPJKU/partitura#89]
Time signature looks like `info(keySignature,[cn, major]).` and causes Error when `partitura.load_match(path, create_part=True)`.

Error log :
```shell
Traceback (most recent call last):
  File "/Users/Documents/2_UNI/03_JKU-PhD/CPJKU/CPCODE/code/mozart_pre.py", line 124, in <module>
    match_pp, match_a, match_sp = pt.load_match(
  File "/Users/Documents/2_UNI/03_JKU-PhD/CPJKU/CPCODE/partitura/partitura/io/importmatch.py", line 1262, in load_match
    spart = part_from_matchfile(mf, match_offset_duration_in_whole=True)
  File "/Users/Documents/2_UNI/03_JKU-PhD/CPJKU/CPCODE/partitura/partitura/io/importmatch.py", line 1581, in part_from_matchfile
    for (ks_beat_time, ks_bar, keys) in mf.key_signatures:
  File "/Users/Documents/2_UNI/03_JKU-PhD/CPJKU/CPCODE/partitura/partitura/io/importmatch.py", line 1154, in key_signatures
    step=ks_info.group("step1"),
AttributeError: 'NoneType' object has no attribute 'group'. Did you mean: 'time_signatures'?
```

**Comment by melkisedeath** [comment]
To address the problem the lines 1142 in develop should be changed:
```python
# remove brackets and only take
# the first key signature
ks = ksl.Value.replace("[", "").replace("]", "").split(",")[0]
```
The split function removes the type of the Time signature when it is defined in match version **3.1**  as :
```shell
info(keySignature,[cn, minor]).
```

The split function exists to address multiple Time Signatures but in this case there is only one.
The error can not be fixed easily and be backward compatible with match files which contain multiple Time Signatures. @huispaty 

This split looks like a hack and needs to be addressed.
